name: I am Mita, Your Housekeeper # 家政婦のミタ

on:
  schedule:
    - cron: '0 23 * * *'

jobs:
  prune_old_releases:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prune old releases
        run: ./util/prunetags.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}
